CREATE TABLE gas_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT NOT NULL DEFAULT 0,
  kind VARCHAR(30) NOT NULL,
  payload TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_gas_records_kind_id ON gas_records(kind, id);
