import { useState, type FormEvent } from "react";
import { Campo, Decimale, Salva, Errore } from "../components/ui";
import { api, messaggioErrore, useLista } from "../api";
import { bandCodes, categories, period, type Saved, type Profile, type Bill, type Offer, type Line, type Category } from "../domain";
export function OfferFields({ value, set }: {
    value: Offer;
    set: (v: Offer) => void;
}) {
    return <><div className="form-grid"><Campo label="Nome offerta" required value={value.name} onChange={e => set({ ...value, name: e.target.value })}/><Campo label="Fornitore" required value={value.provider} onChange={e => set({ ...value, provider: e.target.value })}/><label className="field"><span>Tipo di offerta</span><select value={value.type} onChange={e => set({ ...value, type: e.target.value as Offer["type"] })}><option value="FIXED">Prezzo fisso</option><option value="PSV">Indicizzata PSV</option></select></label><Decimale label={value.type === "FIXED" ? "Prezzo gas (€/Smc)" : "Spread PSV (€/Smc)"} required value={value.type === "FIXED" ? value.price : value.spread} onChange={e => set({ ...value, [value.type === "FIXED" ? "price" : "spread"]: e.target.value, ...(value.type === "PSV" ? { price: "0" } : {}) })}/><Decimale label="QVD quota fissa (€/PDR/mese)" required value={value.qvdFixed} onChange={e => set({ ...value, qvdFixed: e.target.value })}/><Decimale label="CCR (€/Smc)" required value={value.ccr} onChange={e => set({ ...value, ccr: e.target.value })}/><Decimale label="QVD quota variabile (€/Smc)" required value={value.qvdVariable} onChange={e => set({ ...value, qvdVariable: e.target.value })}/></div><Campo label="Note commerciali" value={value.notes} onChange={e => set({ ...value, notes: e.target.value })}/><label className="check"><input type="checkbox" checked={value.active} onChange={e => set({ ...value, active: e.target.checked })}/>Offerta attiva e disponibile per il confronto</label><p className="help">L'offerta definisce le quattro voci materia gas. Il profilo gestore definisce trasporto, oneri, fiscalità e trattamento IVA. Il PSV si inserisce per ogni mese della bolletta.</p></>;
}
export function BillFields({ value, set }: {
    value: Bill;
    set: (v: Bill) => void;
}) {
    const profiles = useLista<Saved<Profile>>("/parametri");
    const change = (i: number, p: Bill["periods"][number]) => set({ ...value, periods: value.periods.map((old, n) => n === i ? p : old) });
    return <><div className="form-grid"><Campo label="Cliente / ragione sociale" required value={value.client} onChange={e => set({ ...value, client: e.target.value })}/><Campo label="PDR" required pattern="[0-9]{14}" maxLength={14} hint="14 cifre" value={value.pdr} onChange={e => set({ ...value, pdr: e.target.value })}/><Campo label="Partita IVA" pattern="[0-9]{11}|" maxLength={11} value={value.partitaIva} onChange={e => set({ ...value, partitaIva: e.target.value })}/><Campo label="Fornitore attuale" required value={value.supplier} onChange={e => set({ ...value, supplier: e.target.value })}/><Campo label="Riferimento fattura" value={value.reference} onChange={e => set({ ...value, reference: e.target.value })}/><Decimale label="Totale fatturato (€)" required value={value.previousTotal} onChange={e => set({ ...value, previousTotal: e.target.value })}/><Decimale label="Altre partite imponibili (€)" min={undefined} required value={value.otherTaxable} onChange={e => set({ ...value, otherTaxable: e.target.value })}/><Decimale label="Altre partite non soggette IVA (€)" min={undefined} required value={value.otherNonTaxable} onChange={e => set({ ...value, otherNonTaxable: e.target.value })}/></div>
 <h3>Consumi mensili gas</h3><p className="help">Mesi consecutivi, da uno a 24. Le quote fisse accettano frazioni di mese. I consumi sono già espressi in Smc.</p>
 {value.periods.map((p, i) => <fieldset className="month-card" key={i}><legend>Periodo {i + 1}</legend><div className="form-grid"><Campo label={`Mese ${i + 1}`} type="month" required value={p.month} onChange={e => change(i, { ...p, month: e.target.value })}/><Decimale label={`Consumo ${i + 1} (Smc)`} required value={p.consumptionSmc} onChange={e => change(i, { ...p, consumptionSmc: e.target.value })}/><Decimale label={`Quote fisse ${i + 1} (mesi)`} required value={p.fixedMonths} onChange={e => change(i, { ...p, fixedMonths: e.target.value })}/><label className="field"><span>Profilo per il periodo {i + 1}</span><select value={p.profileId ?? ""} onChange={e => change(i, { ...p, profileId: e.target.value ? Number(e.target.value) : null, chosenBands: {} })}><option value="">Usa il profilo scelto nel confronto</option>{profiles.data.filter(x => x.data.status !== "ARCHIVED").map(x => <option key={x.id} value={x.id}>{x.data.name}</option>)}</select></label><Decimale label={`PSV ${i + 1} (€/Smc)`} value={p.psv ?? ""} onChange={e => change(i, { ...p, psv: e.target.value || null })}/></div>
 {profiles.data.find(x => x.id === p.profileId)?.data.bands.filter((b, j, all) => all.findIndex(a => a.code === b.code) === j).map(b => <label className="field" key={b.code}><span>Scaglione {b.code} · periodo {i + 1}</span><select value={p.chosenBands[b.code] ?? ""} onChange={e => { const chosenBands = { ...p.chosenBands }; if (e.target.value)
            chosenBands[b.code] = e.target.value;
        else
            delete chosenBands[b.code]; change(i, { ...p, chosenBands }); }}><option value="">Tariffa e scelta esplicita del profilo</option>{profiles.data.find(x => x.id === p.profileId)!.data.bands.filter(x => x.code === b.code).map(x => <option key={x.label}>{x.label}</option>)}</select></label>)}
 <details><summary>Tariffe modificate manualmente · {Object.keys(p.overrides).length} override</summary><p className="help">Ogni modifica conserva tariffa originale, nuovo valore, motivo, operatore e data nel confronto.</p>{Object.entries(p.overrides).map(([code, o]) => <div className="override-row" key={code}><strong>{code}</strong><div className="form-grid three"><Decimale label={`Tariffa ${code} · periodo ${i + 1}`} min={undefined} required value={o.rate} onChange={e => change(i, { ...p, overrides: { ...p.overrides, [code]: { ...o, rate: e.target.value } } })}/><Campo label={`Motivo ${code} · periodo ${i + 1}`} required value={o.reason} onChange={e => change(i, { ...p, overrides: { ...p.overrides, [code]: { ...o, reason: e.target.value } } })}/><Campo label={`Operatore ${code} · periodo ${i + 1}`} required value={o.operator} onChange={e => change(i, { ...p, overrides: { ...p.overrides, [code]: { ...o, operator: e.target.value } } })}/></div><button type="button" className="text-button" onClick={() => { const overrides = { ...p.overrides }; delete overrides[code]; change(i, { ...p, overrides }); }}>Rimuovi override</button></div>)}<label className="field"><span>Aggiungi override · periodo {i + 1}</span><select value="" onChange={e => { if (e.target.value)
            change(i, { ...p, overrides: { ...p.overrides, [e.target.value]: { rate: "", reason: "", operator: "" } } }); }}><option value="">Scegli la voce</option>{["QVD_FIXED", "COMMODITY", "CCR", "QVD_VAR", "DIST_FIXED", "DIST_VAR", "QT", "RS", "UG1", "UG2_FIXED", "RE", "UG3", "UG2_VAR", "EXCISE", "LOCAL_ADDITION"].filter(c => !p.overrides[c]).map(c => <option key={c}>{c}</option>)}</select></label></details>
 {value.periods.length > 1 && <button type="button" className="text-button" onClick={() => set({ ...value, periods: value.periods.filter((_, j) => j !== i) })}>Rimuovi periodo {i + 1}</button>}</fieldset>)}
 <button type="button" className="button secondary" disabled={value.periods.length >= 24} onClick={() => set({ ...value, periods: [...value.periods, period()] })}>Aggiungi mese</button></>;
}
export function ProfileFields({ value, set }: {
    value: Profile;
    set: (v: Profile) => void;
}) {
    const line = (i: number, p: Partial<Line>) => set({ ...value, lines: value.lines.map((old, j) => j === i ? { ...old, ...p } : old) });
    return <><div className="form-grid"><Campo label="Nome del profilo" required value={value.name} onChange={e => set({ ...value, name: e.target.value })}/><Campo label="Fornitore del profilo" required value={value.provider} onChange={e => set({ ...value, provider: e.target.value })}/><Campo label="Area / prodotto" required value={value.area} onChange={e => set({ ...value, area: e.target.value })}/><Campo label="Fonte e periodo dei valori" required value={value.source} onChange={e => set({ ...value, source: e.target.value })}/><Campo label="Validità dal" type="date" required value={value.validFrom} onChange={e => set({ ...value, validFrom: e.target.value })}/><Campo label="Validità al" type="date" value={value.validTo ?? ""} onChange={e => set({ ...value, validTo: e.target.value || null })}/><label className="field"><span>Modalità di calcolo</span><select value={value.mode} onChange={e => set({ ...value, mode: e.target.value as Profile["mode"], ...(e.target.value === "SOURCE_COMPATIBILITY" ? { vatRate: "22" } : {}) })}><option value="SOURCE_COMPATIBILITY">Compatibilità Excel · IVA globale 22%</option><option value="CONFIGURED_RULES">Regole configurate · IVA per voce</option></select></label><Decimale label="IVA globale (%)" max="100" required readOnly={value.mode === "SOURCE_COMPATIBILITY"} value={value.vatRate} onChange={e => set({ ...value, vatRate: e.target.value })}/><label className="field"><span>Stato del profilo</span><select value={value.status} onChange={e => set({ ...value, status: e.target.value as Profile["status"] })}><option value="DRAFT">Bozza · da validare</option><option value="PUBLISHED">Pubblicato · approvato</option><option value="ARCHIVED">Archiviato</option></select></label><Campo label="Responsabile approvazione" required={value.status === "PUBLISHED"} value={value.approvedBy} onChange={e => set({ ...value, approvedBy: e.target.value })}/></div>
 <p className="help">Un profilo pubblicato è immutabile: duplicalo per creare una nuova versione. Le tariffe materia gas dell'offerta prevalgono sui valori del profilo; IVA e scaglioni restano quelli qui configurati.</p>
 {Object.entries(categories).filter(([c]) => value.lines.some(l => l.category === c)).map(([cat, title]) => <fieldset key={cat}><legend>{title}</legend>{value.lines.map((l, i) => l.category === cat ? <div className="tariff-row" key={l.code}><strong>{l.label} <small>{l.code}</small></strong><div className="form-grid three"><Decimale label={`${l.label} (${l.basis === "SMC" ? "€/Smc" : l.basis === "FIXED_MONTH" ? "€/PDR/mese" : "€"})`} min={undefined} required value={l.rate} onChange={e => line(i, { rate: e.target.value })}/>{bandCodes.includes(l.code) && <Campo label={`Scaglione / scelta esplicita ${l.code}`} required value={l.band} hint="Annota la fascia applicata o la scelta manuale verificata" onChange={e => line(i, { band: e.target.value })}/>}{value.mode === "CONFIGURED_RULES" && <><label className="field"><span>Trattamento IVA {l.code}</span><select value={l.vatTreatment} onChange={e => line(i, { vatTreatment: e.target.value as Line["vatTreatment"] })}><option value="GLOBAL">Aliquota globale</option><option value="LINE_RATE">Aliquota della voce</option><option value="NON_TAXABLE">Non soggetta IVA</option></select></label>{l.vatTreatment === "LINE_RATE" && <Decimale label={`IVA ${l.code} (%)`} max="100" required value={l.vatRate} onChange={e => line(i, { vatRate: e.target.value })}/>}</>}</div></div> : null)}</fieldset>)}
 <h3>Scaglioni selezionabili</h3><p className="help">Minimo e massimo sono riferimenti descrittivi. La scelta è esplicita per periodo: nessuna aliquota viene dedotta dal consumo senza una regola approvata.</p>
 {value.bands.map((b, i) => <div className="month-card" key={i}><div className="form-grid three"><label className="field"><span>Voce scaglione {i + 1}</span><select value={b.code} onChange={e => set({ ...value, bands: value.bands.map((o, j) => j === i ? { ...o, code: e.target.value } : o) })}>{bandCodes.map(c => <option key={c}>{c}</option>)}</select></label>{(["label", "min", "max", "rate"] as const).map(k => <Campo key={k} label={`${({ label: "Etichetta", min: "Minimo Smc", max: "Massimo Smc", rate: "Tariffa €/Smc" })[k]} scaglione ${i + 1}`} type={k === "label" ? "text" : "number"} step="any" required={k !== "max"} value={b[k] ?? ""} onChange={e => set({ ...value, bands: value.bands.map((o, j) => j === i ? { ...o, [k]: k === "max" && !e.target.value ? null : e.target.value } : o) })}/>)}</div><button type="button" className="text-button" onClick={() => set({ ...value, bands: value.bands.filter((_, j) => j !== i) })}>Rimuovi scaglione</button></div>)}
 <button type="button" className="button secondary" onClick={() => set({ ...value, bands: [...value.bands, { code: "DIST_VAR", label: "", min: "0", max: null, rate: "0" }] })}>Aggiungi scaglione</button>
 <details><summary>Aggiungi una voce personalizzata</summary><button type="button" className="button secondary" onClick={() => set({ ...value, lines: [...value.lines, { code: `EXTRA_${value.lines.length}`, label: "Voce aggiuntiva", category: "OTHER", basis: "AMOUNT", rate: "0", vatTreatment: "GLOBAL", vatRate: "22", band: "" }] })}>Aggiungi voce</button>{value.lines.map((l, i) => l.code.startsWith("EXTRA_") ? <div className="form-grid" key={l.code}><Campo label={`Descrizione ${l.code}`} required value={l.label} onChange={e => line(i, { label: e.target.value })}/><label className="field"><span>Categoria {l.code}</span><select value={l.category} onChange={e => line(i, { category: e.target.value as Category })}>{Object.entries(categories).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label><label className="field"><span>Base {l.code}</span><select value={l.basis} onChange={e => line(i, { basis: e.target.value as Line["basis"] })}><option value="AMOUNT">Importo €</option><option value="SMC">Consumo Smc</option><option value="FIXED_MONTH">Quote mensili</option></select></label></div> : null)}</details></>;
}
export function EntityForm<T>({ kind, initial, children, onClose, onSaved }: {
    kind: string;
    initial: Saved<T>;
    children: (v: T, set: (v: T) => void) => React.ReactNode;
    onClose: () => void;
    onSaved: () => void;
}) {
    const [value, set] = useState<T>(structuredClone(initial.data));
    const [error, setError] = useState("");
    const [busy, setBusy] = useState(false);
    async function submit(e: FormEvent) { e.preventDefault(); setError(""); setBusy(true); try {
        if (initial.id)
            await api.put(`/${kind}/${initial.id}`, { data: value, version: initial.version });
        else
            await api.post(`/${kind}`, { data: value });
        onSaved();
        onClose();
    }
    catch (e) {
        setError(messaggioErrore(e));
    }
    finally {
        setBusy(false);
    } }
    return <form onSubmit={submit}>{error && <Errore message={error}/>} {children(value, set)}<Salva busy={busy} onCancel={onClose}/></form>;
}
