import { test, expect } from "@playwright/test";
test("quattro Excel, sette sezioni, PDF personalizzato, storico e mobile", async ({ page }) => {
    const errors: string[] = [];
    page.on("pageerror", e => errors.push(e.message));
    await page.goto("/");
    await expect(page.getByRole("navigation").getByRole("link")).toHaveCount(7);
    await page.getByText("Prova con i quattro esempi Excel").click();
    for (const [name, total] of [["GENNAIO-FEBBRAIO", "392,61"], ["FEBBRAIO-MARZO", "896,42"], ["MARZO-APRILE", "408,43"], ["APRILE-MAGGIO", "659,77"]]) {
        await page.getByLabel("Scenario Excel").selectOption(name);
        await page.getByRole("button", { name: "Carica esempio e calcola" }).click();
        await expect(page.getByRole("region", { name: "Risultato del confronto" })).toContainText(total);
    }
    await expect(page.getByText("Maggior costo stimato", { exact: true })).toBeVisible();
    await expect(page.getByRole("region", { name: "Risultato del confronto" })).toContainText("106,33");
    const pdf = page.waitForEvent("download");
    await page.getByRole("button", { name: "Scarica PDF", exact: true }).click();
    expect(await (await pdf).failure()).toBeNull();
    await (await pdf).saveAs("test-results/confronto-gas.pdf");
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({ path: "test-results/gas-desktop.png", fullPage: true });
    await page.getByRole("link", { name: "Impostazioni PDF", exact: true }).click();
    await page.getByRole("radio", { name: /Sintesi cliente/ }).check();
    await page.getByRole("button", { name: "Blu Istituzionale" }).click();
    await page.getByLabel("Nome o studio").fill("Studio Gas Test");
    await expect(page.getByText("PDF aggiornato · formato A4")).toBeVisible();
    await page.getByRole("button", { name: "Salva impostazioni PDF" }).click();
    await expect(page.getByText(/Impostazioni PDF salvate/)).toBeVisible();
    await page.reload();
    await expect(page.getByLabel("Nome o studio")).toHaveValue("Studio Gas Test");
    await expect(page.getByLabel("Codice colore")).toHaveValue("#1E3A8A");
    await page.getByRole("link", { name: "Offerte", exact: true }).click();
    await expect(page.getByRole("heading", { name: "Le tue offerte gas" })).toBeVisible();
    await page.getByRole("button", { name: "Nuova offerta" }).click();
    await page.getByLabel("Nome offerta").fill("Offerta prova manuale");
    await page.getByLabel("Fornitore").fill("Gestore Test");
    await page.getByLabel("Prezzo gas (€/Smc)").fill("0.40");
    await page.getByRole("button", { name: "Salva", exact: true }).click();
    await expect(page.getByText("Offerta prova manuale · Gestore Test", { exact: true })).toBeVisible();
    await page.getByRole("link", { name: "Bollette clienti", exact: true }).click();
    await expect(page.getByRole("heading", { name: "Bollette clienti", exact: true })).toBeVisible();
    await page.getByRole("link", { name: "Parametri gestore", exact: true }).click();
    await expect(page.getByRole("heading", { name: "Parametri del gestore gas" })).toBeVisible();
    await page.getByRole("link", { name: "Fonti ufficiali", exact: true }).click();
    await page.getByLabel("Mese PSV").fill("2024-01");
    await page.getByLabel("PSV (€/Smc)").fill("0.40");
    await page.getByLabel("Fonte verificata").fill("Fonte sintetica per test");
    await page.getByLabel("Motivo / riferimento").fill("Verifica browser");
    await page.getByRole("button", { name: "Salva fonte" }).click();
    await expect(page.getByRole("status")).toContainText("Fonte salvata");
    await page.setViewportSize({ width: 390, height: 844 });
    await page.getByRole("button", { name: "Apri menu" }).click();
    await page.getByRole("link", { name: "Storico", exact: true }).click();
    await page.getByLabel("Cerca cliente, offerta, profilo o operatore").fill("Cliente demo 4");
    await page.getByRole("button", { name: "Apri", exact: true }).first().click();
    await expect(page.getByRole("region", { name: "Risultato del confronto" })).toContainText("659,77");
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
    await page.screenshot({ path: "test-results/gas-mobile.png", fullPage: true });
    expect(errors).toEqual([]);
});
