import { test, expect } from "@playwright/test";
test("inserimento manuale di profilo, offerta e bolletta gas", async ({ page }) => {
    await page.goto("/parametri");
    await page.getByRole("button", { name: "Nuovo profilo" }).click();
    await page.getByLabel("Nome del profilo").fill("Profilo manuale test");
    await page.getByLabel("Fornitore del profilo").fill("Gestore Manuale");
    await page.getByLabel("Area / prodotto").fill("Test locale");
    await page.getByLabel("Fonte e periodo dei valori").fill("Dati sintetici 2026");
    await page.getByLabel("Validità dal").fill("2026-01-01");
    await page.getByLabel("Validità al").fill("2026-12-31");
    for (const code of ["DIST_VAR", "UG2_VAR", "EXCISE", "LOCAL_ADDITION"])
        await page.getByLabel(`Scaglione / scelta esplicita ${code}`).fill("Scelta manuale sintetica: tariffa zero");
    await page.getByLabel("Quota fissa UG2 (€/PDR/mese)").fill("-2");
    await page.getByRole("button", { name: "Salva", exact: true }).click();
    await expect(page.getByText("Profilo manuale test · Gestore Manuale", { exact: true })).toBeVisible();
    await page.getByRole("link", { name: "Offerte", exact: true }).click();
    await page.getByRole("button", { name: "Nuova offerta" }).click();
    await page.getByLabel("Nome offerta").fill("Fissa manuale test");
    await page.getByLabel("Fornitore").fill("Gestore Manuale");
    await page.getByLabel("Prezzo gas (€/Smc)").fill("0.4");
    await page.getByLabel("QVD quota fissa (€/PDR/mese)").fill("5");
    await page.getByRole("button", { name: "Salva", exact: true }).click();
    await page.getByRole("link", { name: "Bollette clienti", exact: true }).click();
    await page.getByRole("button", { name: "Nuova bolletta" }).click();
    await page.getByLabel("Cliente / ragione sociale").fill("Cliente manuale test");
    await page.getByLabel("PDR").fill("00000000000002");
    await page.getByLabel("Fornitore attuale").fill("Fornitore Test");
    await page.getByLabel("Totale fatturato (€)").fill("120");
    await page.getByLabel("Mese 1").fill("2026-01");
    await page.getByLabel("Mese 2").fill("2026-02");
    await page.getByLabel("Consumo 1 (Smc)").fill("100");
    await page.getByLabel("Consumo 2 (Smc)").fill("50");
    await page.getByRole("button", { name: "Salva", exact: true }).click();
    await page.getByRole("link", { name: "Confronto", exact: true }).click();
    await page.getByLabel("Bolletta del cliente").selectOption({ label: "Cliente manuale test · 2026-01" });
    await page.getByLabel("Offerta proposta").selectOption({ label: "Fissa manuale test · Gestore Manuale" });
    await page.getByLabel("Profilo gestore").selectOption({ label: "Profilo manuale test · da validare" });
    await page.getByRole("button", { name: "Calcola confronto" }).click();
    await expect(page.getByRole("region", { name: "Risultato del confronto" })).toContainText("80,52");
    await expect(page.getByRole("region", { name: "Risultato del confronto" })).toContainText("39,48");
    const json = page.waitForEvent("download");
    await page.getByRole("button", { name: "Scarica JSON" }).click();
    expect(await (await json).failure()).toBeNull();
});
